# Generated by Django 3.0.3 on 2020-03-02 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='招生名称')),
                ('desc', models.TextField(default='招生名称', verbose_name='招生名称介绍')),
            ],
            options={
                'verbose_name': '招生名称',
                'verbose_name_plural': '招生名称',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='学院名称')),
                ('desc', models.TextField(default='学院', verbose_name='学院简介')),
            ],
            options={
                'verbose_name': '学院信息',
                'verbose_name_plural': '学院信息',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='学校名称')),
                ('category', models.CharField(choices=[('ptbk', '普通本科'), ('dlxy', '独立学院'), ('zk', '专科（高职）'), ('qt', '其他')], default='ptbk', max_length=4, verbose_name='办学类型')),
                ('heat_rank', models.IntegerField(default=0, verbose_name='全国热度排名')),
                ('tag', models.CharField(choices=[('wu', ' '), ('gb', '公办'), ('211gc', '211工程'), ('985gc', '985工程'), ('yldx', '一流大学建设高校')], default='wu', max_length=5, verbose_name='标签')),
                ('tag1', models.CharField(choices=[('wu', ' '), ('gb', '公办'), ('211gc', '211工程'), ('985gc', '985工程'), ('yldx', '一流大学建设高校')], default='wu', max_length=5, verbose_name='标签1')),
                ('tag2', models.CharField(choices=[('wu', ' '), ('gb', '公办'), ('211gc', '211工程'), ('985gc', '985工程'), ('yldx', '一流大学建设高校')], default='wu', max_length=5, verbose_name='标签2')),
                ('tag3', models.CharField(choices=[('wu', ' '), ('gb', '公办'), ('211gc', '211工程'), ('985gc', '985工程'), ('yldx', '一流大学建设高校')], default='wu', max_length=5, verbose_name='标签3')),
                ('desc', models.TextField(default='大学', verbose_name='学校概况')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='area.City', verbose_name='所在地')),
                ('province', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='area.Province', verbose_name='所属省份')),
            ],
            options={
                'verbose_name': '学校信息',
                'verbose_name_plural': '学校信息',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='专业名称')),
                ('desc', models.TextField(default='专业', verbose_name='专业概况')),
                ('admissionscategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AdmissionsCategory', verbose_name='招生名称')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.College', verbose_name='所属学院')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='所属学校')),
            ],
            options={
                'verbose_name': '专业信息',
                'verbose_name_plural': '专业信息',
            },
        ),
        migrations.AddField(
            model_name='college',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='所属学校'),
        ),
        migrations.AddField(
            model_name='admissionscategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='所属学校'),
        ),
    ]
