# Generated by Django 3.0.3 on 2020-03-02 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=10, verbose_name='批次名')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Province', verbose_name='所在省份')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.IntegerField(default=2015, verbose_name='年份')),
            ],
            options={
                'verbose_name': '年份',
                'verbose_name_plural': '年份',
            },
        ),
        migrations.CreateModel(
            name='ProvinceScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=10, verbose_name='类别')),
                ('score', models.IntegerField(default=0, verbose_name='分数线')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreline.Batch', verbose_name='批次')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Province', verbose_name='所在省份')),
            ],
            options={
                'verbose_name': '省控线',
                'verbose_name_plural': '省控线',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('level', models.CharField(choices=[('bk', '本科'), ('zk', '专科')], default='bk', max_length=5, verbose_name='层次')),
                ('highest', models.IntegerField(default=0, verbose_name='最高分')),
                ('lowest', models.IntegerField(default=0, verbose_name='最低分')),
                ('average', models.FloatField(default=0, verbose_name='平均分')),
                ('place', models.IntegerField(default=0, null=True, verbose_name='位次')),
                ('note', models.CharField(max_length=100, null=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreline.Batch', verbose_name='批次')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Professional', verbose_name='专业')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Province', verbose_name='省份')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='学校')),
                ('year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreline.Year', verbose_name='年份')),
            ],
            options={
                'verbose_name': '专业分数线',
                'verbose_name_plural': '专业分数线',
            },
        ),
    ]
